import assert from 'node:assert/strict';
import { buildQuery, search, ENDPOINT, fields, facets } from '../web/search.js';
import { geometryFor } from '../web/geo.js';
const preflight = await fetch(ENDPOINT, { method: 'OPTIONS', headers: { Origin: 'http://127.0.0.1:4173', 'Access-Control-Request-Method': 'POST', 'Access-Control-Request-Headers': 'content-type' } });
assert.ok(preflight.ok);
assert.equal(preflight.headers.get('access-control-allow-origin'), '*');
assert.match(preflight.headers.get('access-control-allow-methods'), /POST/);
assert.match(preflight.headers.get('access-control-allow-headers'), /content-type/i);
const base = { query: 'kasteel AND gracht', field: 'Omschrijving' };
const result = await search(buildQuery(base), AbortSignal.timeout(30000));
assert.equal(result.hits.total.relation, 'eq');
assert.ok(result.hits.hits.some(hit => hit.highlight?.[fields.description]?.length));
for (const key of Object.keys(facets)) assert.ok(result.aggregations[key].buckets.length, `Facet ${key}`);
const gelderland = result.aggregations.addressRegion.buckets.find(bucket => bucket.key === 'Gelderland');
assert.ok(gelderland);
const filtered = await search(buildQuery({ ...base, filters: { addressRegion: 'Gelderland' } }), AbortSignal.timeout(30000));
assert.equal(filtered.hits.total.value, gelderland.doc_count);
assert.ok(filtered.hits.hits.every(hit => hit._source[fields.addressRegion].includes('Gelderland')));
const page2 = await search(buildQuery({ ...base, page: 1 }), AbortSignal.timeout(30000));
assert.equal(page2.hits.total.value, result.hits.total.value);
assert.notEqual(page2.hits.hits[0]._id, result.hits.hits[0]._id);
const geometries = result.hits.hits.map(hit => geometryFor(hit._source)?.kind ?? 'geen');
assert.ok(geometries.some(kind => kind !== 'geen'), 'Geometrie op de kaart');
console.log(JSON.stringify({ cors: 'OK', geometrie: Object.fromEntries(['punt', 'vlak', 'geen'].map(kind => [kind, geometries.filter(k => k === kind).length])), total: result.hits.total.value, gelderland: filtered.hits.total.value, facets: Object.fromEntries(Object.entries(result.aggregations).map(([key, value]) => [key, value.buckets.length])), highlighting: 'OK', pagination: 'OK' }, null, 2));
